packages:
  - apps/*
  - packages/*

catalog:
  arktype: ^2.1.20

catalogs:
  build:
    tsdown: ^0.13.0
  frontend:
    react: ^19.1.0
  test:
    '@vitejs/plugin-react': ^4.4.1
    '@vitest/browser': ^3.1.3
    playwright: ^1.52.0
    vitest: ^3.2.4
    vitest-browser-react: ^0.1.1
  types:
    '@webgpu/types': ^0.1.64
    typescript: ^5.8.3

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
